// src/lib/jobs.constant.ts

export const workMode = {
  remote: 'REMOTE',
  office: 'ONSITE',
  hybrid: 'HYBRID',
};

export enum WorkModeEnums {
  REMOTE = 'REMOTE',
  OFFICE = 'ONSITE',
  HYBRID = 'HYBRID',
}

export enum JobTypeEnums {
  FULL_TIME = 'FULL_TIME',
  PART_TIME = 'PART_TIME',
  CONTRACT = 'CONTRACT',
  TEMPORARY = 'TEMPORARY',
  INTERNSHIP = 'INTERNSHIP',
}

export enum SortByEnums {
  POSTEDAT_ASC = 'postedat_asc',
  POSTEDAT_DESC = 'postedat_desc',
}

export const filters = {
  workMode: [
    { id: 1, label: 'Remote', value: workMode.remote },
    { id: 2, label: 'Office', value: workMode.office },
    { id: 3, label: 'Hybrid', value: workMode.hybrid },
  ],
  jobType: [ // Renamed from workType to jobType
    { id: 1, label: "FULL_TIME", value: JobTypeEnums.FULL_TIME },
    { id: 2, label: "PART_TIME", value: JobTypeEnums.PART_TIME },
    { id: 3, label: "CONTRACT", value: JobTypeEnums.CONTRACT },
    { id: 4, label: "TEMPORARY", value: JobTypeEnums.TEMPORARY },
    { id: 5, label: "INTERNSHIP", value: JobTypeEnums.INTERNSHIP },
  ],
  chooseCurrency: [
    { id: 1, label: 'INR', value: 'INR' },
    { id: 2, label: 'USD', value: 'USD' },
  ],
  salaryRange: [
    { id: 1, label: '$0-$5k', value: '0-5000' },
    { id: 2, label: '$5-$10k', value: '5000-10000' },
    { id: 3, label: '$10-$30k', value: '10000-30000' },
    { id: 4, label: '$30-$50k', value: '30000-50000' },
    { id: 5, label: '$50k or above', value: '50000-above' },
  ],
  location: [
    { id: 1, label: 'Bangalore', value: 'bangalore' },
    { id: 2, label: 'New Delhi', value: 'new delhi' },
    { id: 3, label: 'Mumbai', value: 'mumbai' },
    { id: 4, label: 'Pune', value: 'pune' },
    { id: 5, label: 'Hyderabad', value: 'hyderabad' },
    { id: 6, label: 'Chennai', value: 'chennai' },
    { id: 7, label: 'Kolkata', value: 'kolkata' },
    { id: 8, label: 'Ahmedabad', value: 'ahmedabad' },
    { id: 9, label: 'Jaipur', value: 'jaipur' },
    { id: 10, label: 'Surat', value: 'surat' },
  ],
  experienceLevels: [
    { id: 1, label: '0-1 year', value: '0' },
    { id: 2, label: '1-2 years', value: '1' },
    { id: 3, label: '2-4 years', value: '2' },
    { id: 4, label: '4-8 years', value: '4' },
    { id: 5, label: '8 or above', value: '8' },
  ],
  roleType: [
    { id: 1, label: "Software Developer", value: "software-developer" },
    { id: 2, label: "Data Scientist", value: "data-scientist" },
    { id: 3, label: "Project Manager", value: "project-manager" },
    { id: 4, label: "Graphic Designer", value: "graphic-designer" },
    { id: 5, label: "Marketing Manager", value: "marketing-manager" },
    { id: 6, label: "Content Writer", value: "content-writer" },
    { id: 7, label: "Sales Executive", value: "sales-executive" },
    { id: 8, label: "Human Resources Manager", value: "human-resources-manager" },
    { id: 9, label: "Financial Analyst", value: "financial-analyst" },
    { id: 10, label: "Customer Service Representative", value: "customer-service-representative" },
    { id: 11, label: "Network Engineer", value: "network-engineer" },
    { id: 12, label: "Cybersecurity Specialist", value: "cybersecurity-specialist" },
    { id: 13, label: "UI/UX Designer", value: "ui-ux-designer" },
    { id: 14, label: "Product Manager", value: "product-manager" },
    { id: 15, label: "Operations Manager", value: "operations-manager" },
    { id: 16, label: "Quality Assurance Engineer", value: "quality-assurance-engineer" },
    { id: 17, label: "Business Analyst", value: "business-analyst" },
    { id: 18, label: "Accountant", value: "accountant" },
    { id: 19, label: "Administrative Assistant", value: "administrative-assistant" },
    { id: 20, label: "Recruiter", value: "recruiter" },
    { id: 21, label: "DevOps Engineer", value: "devops-engineer" },
    { id: 22, label: "Machine Learning Engineer", value: "machine-learning-engineer" },
    { id: 23, label: "Research Scientist", value: "research-scientist" },
    { id: 24, label: "Logistics Coordinator", value: "logistics-coordinator" },
    { id: 25, label: "Event Planner", value: "event-planner" },
    { id: 26, label: "Healthcare Administrator", value: "healthcare-administrator" },
    { id: 27, label: "Pharmacist", value: "pharmacist" },
    { id: 28, label: "Civil Engineer", value: "civil-engineer" },
    { id: 29, label: "Mechanical Engineer", value: "mechanical-engineer" },
    { id: 30, label: "Electrical Engineer", value: "electrical-engineer" },
    { id: 31, label: "Legal Advisor", value: "legal-advisor" },
    { id: 32, label: "Teacher", value: "teacher" },
    { id: 33, label: "Chef", value: "chef" },
    { id: 34, label: "Retail Manager", value: "retail-manager" },
    { id: 35, label: "Psychologist", value: "psychologist" },
    { id: 36, label: "Dentist", value: "dentist" },
    { id: 37, label: "Nurse", value: "nurse" },
    { id: 38, label: "Physician", value: "physician" },
    { id: 39, label: "Veterinarian", value: "veterinarian" },
    { id: 40, label: "Architect", value: "architect" },
    { id: 41, label: "Urban Planner", value: "urban-planner" },
    { id: 42, label: "Environmental Scientist", value: "environmental-scientist" },
    { id: 43, label: "Journalist", value: "journalist" },
    { id: 44, label: "Photographer", value: "photographer" },
    { id: 45, label: "Actor", value: "actor" },
    { id: 46, label: "Musician", value: "musician" },
    { id: 47, label: "Animator", value: "animator" },
    { id: 48, label: "Video Editor", value: "video-editor" },
    { id: 49, label: "Social Media Manager", value: "social-media-manager" },
    { id: 50, label: "Translator", value: "translator" },
    { id: 51, label: "Web Developer", value: "web-developer" },
    { id: 52, label: "Database Administrator", value: "database-administrator" },
    { id: 53, label: "SEO Specialist", value: "seo-specialist" },
    { id: 54, label: "Digital Marketing Specialist", value: "digital-marketing-specialist" },
    { id: 55, label: "Technical Support Engineer", value: "technical-support-engineer" },
    { id: 56, label: "E-commerce Manager", value: "e-commerce-manager" },
    { id: 57, label: "Supply Chain Manager", value: "supply-chain-manager" },
    { id: 58, label: "Product Designer", value: "product-designer" },
    { id: 59, label: "Cloud Solutions Architect", value: "cloud-solutions-architect" },
    { id: 60, label: "Data Engineer", value: "data-engineer" },
    { id: 61, label: "Blockchain Developer", value: "blockchain-developer" },
    { id: 62, label: "Copywriter", value: "copywriter" },
    { id: 63, label: "Public Relations Specialist", value: "public-relations-specialist" },
    { id: 64, label: "Biotech Researcher", value: "biotech-researcher" },
    { id: 65, label: "Clinical Research Coordinator", value: "clinical-research-coordinator" },
    { id: 66, label: "Insurance Agent", value: "insurance-agent" },
    { id: 67, label: "Loan Officer", value: "loan-officer" },
    { id: 68, label: "Real Estate Agent", value: "real-estate-agent" },
    { id: 69, label: "Mobile App Developer", value: "mobile-app-developer" },
    { id: 70, label: "Human Resources Specialist", value: "human-resources-specialist" },
    { id: 71, label: "Compliance Officer", value: "compliance-officer" },
    { id: 72, label: "Technical Writer", value: "technical-writer" },
    { id: 73, label: "Customer Success Manager", value: "customer-success-manager" },
    { id: 74, label: "Data Analyst", value: "data-analyst" },
    { id: 75, label: "Electrician", value: "electrician" },
    { id: 76, label: "Plumber", value: "plumber" },
    { id: 77, label: "Carpenter", value: "carpenter" },
    { id: 78, label: "Fitness Trainer", value: "fitness-trainer" },
    { id: 79, label: "Yoga Instructor", value: "yoga-instructor" },
    { id: 80, label: "Life Coach", value: "life-coach" },
    { id: 81, label: "Interior Designer", value: "interior-designer" },
    { id: 82, label: "Fashion Designer", value: "fashion-designer" },
    { id: 83, label: "Event Coordinator", value: "event-coordinator" },
    { id: 84, label: "Real Estate Appraiser", value: "real-estate-appraiser" },
    { id: 85, label: "Bartender", value: "bartender" },
    { id: 86, label: "Waiter/Waitress", value: "waiter-waitress" },
    { id: 87, label: "Security Guard", value: "security-guard" },
    { id: 88, label: "Warehouse Associate", value: "warehouse-associate" },
    { id: 89, label: "Medical Coder", value: "medical-coder" },
    { id: 90, label: "Pharmacy Technician", value: "pharmacy-technician" },
    { id: 91, label: "Construction Manager", value: "construction-manager" },
    { id: 92, label: "Automotive Technician", value: "automotive-technician" },
    { id: 93, label: "Airline Pilot", value: "airline-pilot" },
    { id: 94, label: "Flight Attendant", value: "flight-attendant" },
    { id: 95, label: "Meteorologist", value: "meteorologist" },
    { id: 96, label: "Statistician", value: "statistician" },
    { id: 97, label: "Compliance Analyst", value: "compliance-analyst" },
    { id: 98, label: "Financial Planner", value: "financial-planner" },
    { id: 99, label: "Risk Analyst", value: "risk-analyst" },
    { id: 100, label: "Quality Control Inspector", value: "quality-control-inspector" },
  ],
};

export const jobSorting = [
  { id: 1, label: 'Latest Jobs', value: SortByEnums.POSTEDAT_DESC },
  { id: 2, label: 'Oldest Jobs', value: SortByEnums.POSTEDAT_ASC },
];
